In [2]:
import numpy as np
a = np.array([1, 2, 3, 4])
print("Массив из списка:", a)

Массив из списка: [1 2 3 4]


In [6]:
zeros_arr = np.zeros((2, 3))        # массив из нулей размером 2×3
ones_arr = np.ones(5)               # массив из пяти единиц
arange_arr = np.arange(0, 10, 2)    # [0, 2, 4, 6, 8]
print("zeros:\n", zeros_arr)
print("ones:", ones_arr)
print("arange:", arange_arr)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones: [1. 1. 1. 1. 1.]
arange: [0 2 4 6 8]


In [7]:
print("Форма shape:", zeros_arr.shape)     
print("Тип данных dtype:", zeros_arr.dtype) 

Форма shape: (2, 3)
Тип данных dtype: float64


In [8]:
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
# Получение отдельного элемента
element = matrix[1, 2]  # второй ряд, третий столбец 
print("\nЭлемент [1, 2]:", element)
# Извлечение подмассива с помощью среза
sub_arr = matrix[0:2, 1:3]  # первые две строки, столбцы 1 и 2
print("Подмассив:\n", sub_arr)


Элемент [1, 2]: 60
Подмассив:
 [[20 30]
 [50 60]]


In [9]:
# Два одинаковых по размеру массива
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Поэлементное сложение и умножение
summa = a + b          # [5, 7, 9]
prod = a * b         # [4, 10, 18]

print("\nПоэлементное сложение:", summa)
print("\nПоэлементное умножение:", prod)

# Вычисление средней величины
mean_val = a.mean()     # среднее арифметическое
print("\nСреднее значение массива:", mean_val)

# Статистика по массиву 2D
matrix_mean_all = matrix.mean()           # среднее по всем элементам
matrix_mean_rows = matrix.mean(axis=1)    # среднее по строкам

print("\nСреднее по всему:", matrix_mean_all)
print("\nСреднее по строкам:", matrix_mean_rows)


Поэлементное сложение: [5 7 9]

Поэлементное умножение: [ 4 10 18]

Среднее значение массива: 2.0

Среднее по всему: 50.0

Среднее по строкам: [20. 50. 80.]
